# Appendix A: Introduction to PyTorch

Reference: `LLMs-from-scratch/appendix-A/`


In [1]:
import torch
import torch 
import numpy as np
import torch.nn as nn
import torch.optim as optim

## 1. Tensors & Operations

**Scalars, vectors, matrices, and tensors**

In [2]:
# Verify GPU
print(f"PyTorch: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

PyTorch: 2.6.0+cu124
CUDA available: True
GPU: NVIDIA GeForce RTX 4050 Laptop GPU


In [3]:
# create tensors of different dimensions
tensor_0d = torch.tensor(42)  # Scalar (0D)
tensor_1d = torch.tensor([1, 2, 3])  # Vector
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Matrix (2D)
tensor_3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3D Tensor

print("0D Tensor (Scalar):")
print(tensor_0d)
print("\n1D Tensor (Vector):")
print(tensor_1d)
print("\n2D Tensor (Matrix):")
print(tensor_2d)
print("\n3D Tensor:")
print(tensor_3d)

0D Tensor (Scalar):
tensor(42)

1D Tensor (Vector):
tensor([1, 2, 3])

2D Tensor (Matrix):
tensor([[1, 2, 3],
        [4, 5, 6]])

3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [4]:
#Basic tensor operations
a = torch.tensor([1, 2, 3], dtype=torch.float32)
b = torch.tensor([4, 5, 6], dtype=torch.float32)

print(a + b)  # Element-wise addition
print(a * b)  # Element-wise multiplication
print(a @ b)  # Dot product

#reshaping tensors
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
reshaped_tensor = tensor.reshape(3, 2)  # Reshape to 3 rows and 2 columns
print("original shape:", tensor.shape)
print("reshaped shape:", reshaped_tensor.shape)  

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor(32.)
original shape: torch.Size([2, 3])
reshaped shape: torch.Size([3, 2])


##  2. Autograd

In [5]:
#Autograd: PyTorch's automatic differentiation engine
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)  # Create a tensor with gradient tracking
y = x ** 2  # Compute y = x^2
y.sum().backward() # Compute gradients (dy/dx)
print("x:", x)
print("gradients:", x.grad)

x: tensor([1., 2., 3.], requires_grad=True)
gradients: tensor([2., 4., 6.])


## 3. Neural Networks with nn.Module

In [6]:
# Define a simple feedforward neural network (onelayer)
model = nn.Linear(in_features=4, out_features=1)  # Input size: 4, Output size: 1
print("Weight shape:", model.weight.shape)
print("Bias shape:", model.bias.shape)

#forward pass 2 samples, 4 features each
x = torch.tensor([[1.0, 2.0, 3.0,4.0],[5.0, 6.0,7.0, 8.0]])  # Input tensor (batch size: 2, features: 4)

output = model(x)  # Forward pass
print("Input shape:", x.shape)
print("Output shape:", output.shape)

Weight shape: torch.Size([1, 4])
Bias shape: torch.Size([1])
Input shape: torch.Size([2, 4])
Output shape: torch.Size([2, 1])


## 4. Training Loop Basics

In [7]:
# 1. synthetic data : y = 2x + 1 
x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])  # Input data (4 samples, 1 feature)
y = torch.tensor([[3.0], [5.0], [7.0], [9.0]])  # Target data (4 samples, 1 target)

# 2. model
model = nn.Linear(in_features=1, out_features=1)  # Simple linear model
loss_fn = nn.MSELoss()  # Mean Squared Error loss
optimizer = optim.SGD(model.parameters(), lr=0.01)  # Stochastic Gradient Descent optimizer

# 3. training loop
for epoch in range(100):
    predictions = model(x)  # Forward pass
    loss = loss_fn(predictions, y)  # Compute loss
    optimizer.zero_grad()  # Clear gradients
    loss.backward()  # Backpropagation
    optimizer.step()  # Update weights
# Test the trained model
print(f"Trained: y ≈ {model.weight.item():.2f}*x + {model.bias.item():.2f}")
print(f"Expected: y = 2*x + 1")

Trained: y ≈ 2.04*x + 0.89
Expected: y = 2*x + 1


## 5. GPU basics    

In [8]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # Move a tensor to GPU
    x = torch.tensor([1.0, 2.0, 3.0]).to(device)
    print("Tensor on GPU:", x.device)

Using: cuda
GPU: NVIDIA GeForce RTX 4050 Laptop GPU
Memory: 6.4 GB
Tensor on GPU: cuda:0
